# Generated by Django 3.2 on 2022-10-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='checked',
            new_name='isComplete',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
