# Generated by Django 3.2 on 2022-10-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20221026_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
